name: Build, Push Docker Image, and Update K8s Config

on:
  push:
    branches:
      - main

env:
  DPP_CONFIG_DIR: admin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the commit tag
        id: vars
        run: echo "::set-output name=COMMIT_TAG::$(git rev-parse --short HEAD)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.COMMIT_TAG }}
          build-args: |
            NEXT_PUBLIC_BASE_URL=${{env.NEXT_PUBLIC_BASE_URL}}
            NEXT_PUBLIC_ML_FILE_UPLOAD=${{env.NEXT_PUBLIC_ML_FILE_UPLOAD}}

      - name: Post build cleanup
        run: docker builder prune -f

      - name: Reset working directory
        run: cd /home/runner/work/
